T0 19 new arrivals
SD-0924/backend-final-1 pull request #10
Opened 2024-11-25 20:45 UTC by AlaaYa7ia

New arrivals should be any products that have been created for 3 months for example if you are in April, any products that were created in January will be new arrivals.

1- Routs: 

**GET /api/products/new-arrivals - Get new arrivals (with pagination)**

POST /api/products - Add a new product.

PUT /api/products/:id - Update product details (e.g., price, stock, etc.).

DELETE /api/products/:id - Delete a product.

+ Validation

2- productsController

3- productRepository

4- productService

**5- updated the product model (I'm not sure if I need it without the testing)**
------

**Note: unit tests will be in another PR.**

2024-11-25 20:46 UTC, AlaaYa7ia commented on src/controllers/userController.ts
> +import { Request, Response } from "express";
I didn't change anything here, it's only automatic formating.

2024-11-25 20:49 UTC, AlaaYa7ia commented on src/controllers/userController.ts
> -import { verifyPassword } from '../services/userService';
added these two lines together only,  I didn't change the rest of the file, it's only automatic formatting.

2024-11-26 07:56 UTC, batooldshilleh approved these changes
Great job!

2024-11-26 08:19 UTC, Lojain-Abdalrazaq commented
Great job, Alaa! 🙏 I noticed that the `Product` model is missing the image URL property. The product image should be stored in Firebase Storage.

2024-11-26 08:25 UTC, Lojain-Abdalrazaq requested changes
Great job, Alaa!!! 🙏 I noticed that the `Product` model is missing the image URL property. The product image should be stored in Firebase Storage, and the URL should represent the image URL in Firebase.

2024-11-26 10:55 UTC, merged